definitions:
  domain.ServerStatus:
    enum:
    - STARTING
    - RUNNING
    - STOPPING
    - STOPPED
    type: string
    x-enum-varnames:
    - Starting
    - Running
    - Stopping
    - Stopped
  domain.ServerType:
    enum:
    - SMALL
    - MEDIUM
    - LARGE
    type: string
    x-enum-varnames:
    - Small
    - Medium
    - Large
  requests.CreateServerRequest:
    properties:
      name:
        description: |-
          Name of the server
          example: ESGI
        type: string
      status:
        allOf:
        - $ref: '#/definitions/domain.ServerStatus'
        description: |-
          Status of the server
          example: STARTED | RUNNING | STOPPING | STOPPED
        enum:
        - STARTING
        - RUNNING
        - STOPPING
        - STOPPED
      type:
        allOf:
        - $ref: '#/definitions/domain.ServerType'
        description: |-
          Type of the server
          example: SMALL | MEDIUM | LARGE
        enum:
        - SMALL
        - MEDIUM
        - LARGE
    required:
    - name
    - status
    - type
    type: object
  responses.APIError:
    properties:
      code:
        description: |-
          Code of the error
          example: internal_server_error
        type: string
      context:
        additionalProperties: true
        description: |-
          Context of the error
          example: {"body": "body of the request"}
        type: object
      error:
        description: |-
          OriginalError is the original error
          example: Error parsing JSON
        type: string
      message:
        description: |-
          Message of the error
          example: Internal server error
        type: string
      status:
        description: |-
          Status of the error
          example: 500
        type: integer
    type: object
  responses.ServerResponse:
    properties:
      id:
        description: |-
          ID unique identifier of the server
          example: 1
        type: integer
      name:
        description: |-
          Name of the server
          example: ESGI
        type: string
      status:
        description: |-
          Status of the server
          example: STARTED | RUNNING | STOPPING | STOPPED
        type: string
      type:
        description: |-
          Type of the server
          example: SMALL | MEDIUM | LARGE
        type: string
    type: object
info:
  contact: {}
paths:
  /servers:
    get:
      consumes:
      - application/json
      description: Find all servers
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/responses.ServerResponse'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.APIError'
      summary: Find all servers
      tags:
      - Servers
    post:
      consumes:
      - application/json
      description: Create a server
      parameters:
      - description: Server
        in: body
        name: server
        required: true
        schema:
          $ref: '#/definitions/requests.CreateServerRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/responses.ServerResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.APIError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.APIError'
      summary: Create a server
      tags:
      - Servers
  /servers/{id}:
    get:
      consumes:
      - application/json
      description: Find server by ID
      parameters:
      - description: Server ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.ServerResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/responses.APIError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.APIError'
      summary: Find server by ID
      tags:
      - Servers
swagger: "2.0"
